apiVersion: v1
kind: Service
metadata:
  name: assistant-service
  labels:
    app: assistant-service
spec:
  selector:
    app: assistant-service
  ports:
    - name: http
      port: 3014
      targetPort: 3014
      protocol: TCP
  type: ClusterIP